CafeApps.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CafeApps.Web.Models;
using static CafeApps.Web.Models.User;

namespace CafeApps.Web.Controllers
{
    public class AdminController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Admin
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("AdminLogin");
            }
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult DetailsOfUser(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        public ActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdminLogin(User user)
        {
            var CheckUser = db.Users.Where(u => u.Username == user.Username && u.Role ==Roles.Admin).SingleOrDefault();

            if (CheckUser != null)
            {
                if (CheckUser.Password != user.Password)
                {
                    ViewBag.Error = "Invalid user";
                    return View();
                }
                Session["Id"] = CheckUser.UserId;
                return RedirectToAction("Index");
            }
            ViewBag.Error = "Invalid user";
            return View();
        }

        public ActionResult CreateUser()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("AdminLogin");
            }
            return View();
        }

        [HttpPost]
        public ActionResult CreateUser(User user)
        {
            db.Users.Add(user);
            return RedirectToAction("Index");
        }

        // GET: Users/Edit/5
        public ActionResult EditUser(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUser(User user)
        {
            //var updateUser = db.Users.Where(u => u.UserId == user.UserId).SingleOrDefault();
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET: Users/Delete/5
        public ActionResult DeleteUser(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ViewAllMenu()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("AdminLogin");
            }
            return View(db.Menus.ToList());
        }

        public ActionResult AddMenu()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("AdminLogin");
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddMenu(Menu menu)
        {
            string filename = Path.GetFileNameWithoutExtension(menu.ImageFile.FileName);
            string extension=Path.GetExtension(menu.ImageFile.FileName);
            filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
            menu.Image = "~/Image/" + filename;
            filename = Path.Combine(Server.MapPath("~/Image/"), filename);
            menu.ImageFile.SaveAs(filename);
            db.Menus.Add(menu);
            db.SaveChanges();
            return RedirectToAction("ViewAllMenu");
        }

        public ActionResult EditMenu(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        [HttpPost]
        public ActionResult EditMenu(Menu menu)
        {
            if (ModelState.IsValid)
            { 
                string filename = Path.GetFileNameWithoutExtension(menu.ImageFile.FileName);
                string extension = Path.GetExtension(menu.ImageFile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                menu.Image = "~/Image/" + filename;
                filename = Path.Combine(Server.MapPath("~/Image/"), filename);
                menu.ImageFile.SaveAs(filename);
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewAllMenu");
            }
            return View(menu);
        }

        public ActionResult DeleteMenu(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("DeleteMenu")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMenuConfirmed(int id)
        {
            Menu menu = db.Menus.Find(id);
            db.Menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DetailsOfMenu(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }
        public ActionResult AddTable()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("AdminLogin");
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddTable(Table table)
        {
            db.Tables.Add(table);
            db.SaveChanges();
            return RedirectToAction("ViewTableStatus");
        }

        public ActionResult ViewTableStatus()
        {
            if (Session["Id"] != null)
            {
                return View(db.Tables.ToList());
            }
            return RedirectToAction("AdminLogin");
        }

        public ActionResult Logout()
        {
            Session["Id"] = null;
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CafeApps.Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CafeApps.Web.Models;
using static CafeApps.Web.Models.Table;
using static CafeApps.Web.Models.User;

namespace CafeApps.Web.Controllers
{
    public class CustomerController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Customer
        public ActionResult Index()
        {
            if (Session["UserId"] != null)
            {
                return View(db.Menus.ToList());
                
            }
            return RedirectToAction("CustomerLogin");
        }

        public ActionResult CustomerLogin()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CustomerLogin(User user)
        {
            var CheckUser = db.Users.Where(u => u.Username == user.Username && u.Role == Roles.Customer).SingleOrDefault();

            if (CheckUser != null)
            {
                if (CheckUser.Password != user.Password)
                {
                    ViewBag.Error = "Invalid user";
                    return View();
                }
                Session["UserId"] = CheckUser.UserId;
                return RedirectToAction("Index");
            }
            ViewBag.Error = "Invalid user";
            return View();
        }

        [HttpPost]
        public ActionResult AddMenuToCart(int id)
        {
            Cart cart = new Cart();
            cart.UsersId = Convert.ToInt32(Session["UserId"]);
            var getFoodId = db.Menus.SingleOrDefault(m => m.MenuId == id);
            var getCart = db.Carts.SingleOrDefault(c => c.MenusId == id);

            if (getCart != null)
            {

                getCart.Quantity += 1;
                getCart.TotalAmount = getCart.Quantity * getFoodId.Price;

                db.Entry(getCart).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { Message = true, Msg = getFoodId.FoodName + " already added into cart" }, JsonRequestBehavior.AllowGet);
            }

            else
            {
                cart.MenusId = id;
                cart.Price = getFoodId.Price;
                cart.Quantity = 1;
                cart.TotalAmount = getFoodId.Price * cart.Quantity;
                cart.FoodName = getFoodId.FoodName;
                db.Carts.Add(cart);
                db.SaveChanges();
                return Json(new { Message = false, Msg = getFoodId.FoodName + " added into cart" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ViewCart()
        {
            if (Session["UserId"] != null)
            {
                int id = Convert.ToInt32(Session["UserId"]);
                return View(db.Carts.Where(c => c.UsersId == id).ToList());
            }
            return RedirectToAction("CustomerLogin");
        }

        [HttpPost]
        public ActionResult AddQuantity(int id)
        {
            var getCart = db.Carts.SingleOrDefault(c => c.CartId == id);
            var getFoodId = db.Menus.SingleOrDefault(m => m.MenuId == getCart.MenusId);
            if (getCart != null)
            {
                getCart.Quantity += 1;
                getCart.TotalAmount = getCart.Quantity * getFoodId.Price;
                db.Entry(getCart).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { Message = true, Msg = getFoodId.FoodName + " already added into cart" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Message = false, Msg = "Invalid Item" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeductQuantity(int id)
        {
            var getCart = db.Carts.SingleOrDefault(c => c.CartId == id);
            var getFoodId = db.Menus.SingleOrDefault(m => m.MenuId == getCart.MenusId);
            if (getCart != null)
            {
                getCart.Quantity -= 1;
                getCart.TotalAmount = getCart.Quantity * getFoodId.Price;
                if (getCart.Quantity == 0)
                {
                    db.Carts.Remove(getCart);
                    db.SaveChanges();
                }
                db.Entry(getCart).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { Message = true, Msg = getFoodId.FoodName + " already deduct from cart" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Message = false, Msg = "Invalid Item" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteFood(int id)
        {
            var getCart = db.Carts.SingleOrDefault(c => c.CartId == id);
            var getFoodId = db.Menus.SingleOrDefault(m => m.MenuId == getCart.MenusId);

            db.Carts.Remove(getCart);
            db.SaveChanges();
            return Json(new { Message = true, Msg = getFoodId.FoodName + " remove from cart" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ConfirmOrder()
        {
            Table table = new Table();
            if (Session["UserId"] != null)
            {
                int TableId = 1;
                //table.TableId = TableId;
                var GetTable = db.Tables.SingleOrDefault(t => t.TableId == TableId);
                int Id = Convert.ToInt32(Session["UserId"]);
                var User = db.Users.SingleOrDefault(u => u.UserId == Id);
                if (User != null)
                {
                   
                    if (table.TableId == TableId && table.Status == TableStatus.Occupied)
                    {
                        TableId++;

                        if (table.TableId == TableId && table.Status != TableStatus.Occupied)
                        {
                            GetTable.UserId = User.UserId;
                            GetTable.Status = TableStatus.Occupied;
                            db.Entry(GetTable).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                    }
                    GetTable.UserId = User.UserId;
                    GetTable.Status = TableStatus.Occupied;
                    db.Entry(GetTable).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return View(GetTable);
            }
            return RedirectToAction("CustomerLogin");
        }

        public ActionResult Logout()
        {
            Session["UserId"] = null;
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CafeApps.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe Apps", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("View All User", "Index", "Admin")</li>
                    <li>@Html.ActionLink("View All Menu", "ViewAllMenu", "Admin")</li>
                    <li>@Html.ActionLink("View All Table Status", "ViewTableStatus", "Admin")</li>
                    <li>@Html.ActionLink("Logout","Logout","Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeApps.Web/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe Apps", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("View Menu", "Index", "Customer")</li>
                    <li>@Html.ActionLink("View Cart", "ViewCart", "Customer")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Customer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeApps.Web/Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe Apps", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("View All Table", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Employee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CafeApps.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cafe Apps", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Customer", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Cashier", "Index", "Employee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>